version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 461655781674.dkr.ecr.ca-central-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t my-docker-repo .
      - BUILD_ID=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 15) 
      - echo "Building with Build ID $BUILD_ID"
      - docker tag my-docker-repo:latest 461655781674.dkr.ecr.ca-central-1.amazonaws.com/my-docker-repo:$BUILD_ID
      - echo "461655781674.dkr.ecr.ca-central-1.amazonaws.com/my-docker-repo:$BUILD_ID" > image_tag.txt
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 461655781674.dkr.ecr.ca-central-1.amazonaws.com/my-docker-repo:$BUILD_ID
      - echo Writing image definitions file...
      - echo Updating ArgoCD GitOps repository...
      - chmod +x update_argocd.sh
      - ./update_argocd.sh  
       
artifacts:
  files:
    - image_tag.txt




