version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 461655781674.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t argocd-repo . 
      - docker tag argocd-repo:latest 461655781674.dkr.ecr.ap-south-1.amazonaws.com/argocd-repo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 461655781674.dkr.ecr.ap-south-1.amazonaws.com/argocd-repo:latest
      - echo Writing image definitions file...
      - echo Updating ArgoCD GitOps repository...
      - git clone https://github.com/sagarbarawakar711/ArgoCD-Repo.git
      - cd ArgoCD-Repo
      - sed -i "s|image:|image: 461655781674.dkr.ecr.ap-south-1.amazonaws.com/argocd-repo:latest|" deployment.yaml
      - git config --global user.email "sagarbarawakar1993@gmail.com"
      - git config --global user.name "Sagar.Barawakar"
      - git add deployment.yaml
      - git commit -m "Updated image to latest"
      - git push origin main
       
artifacts:
  files:
    - imagedefinitions.json
